language: node_js
node_js:
  - "6.11.5"
sript:
  - yarn install
install:
  - yarn add pug
  - yarn global add firebase-tools
  - yarn add -D jest
  - yarn add -D babel-plugin-transform-es2015-modules-commonjs
  - cd functions && yarn jest
affter_success:
  - firebase deploy --token $FIREBASE_TOKEN