language: node_js
node_js:
  - "6.11.5"
sript:
  - yarn install
install:
  - yarn install -g firebase-tools
  - yarn install jest --only=dev
  - yarn install babel-plugin-transform-es2015-modules-commonjs --dev
affter_success:
  - firebase deploy --token $FIREBASE_TOKEN