language: node_js
node_js:
  - "6.11.5"
sript:
  - yarn install
install:
  - yarn add chai
  - yarn add express
  - yarn add pug
  - yarn add firebase
  - yarn add firebase-admin
  - yarn add firebase-functions
  - yarn global add firebase-tools
  - yarn add -D jest
  - yarn add -D babel-plugin-transform-es2015-modules-commonjs
  - yarn install
after_success:
  - firebase deploy --token $FIREBASE_TOKEN