language: node_js
node_js:
  - "6.11.5"
sript:
  - yarn install
install:
  - yarn global add firebase-tools
  - yarn add -D jest --only=dev
  - yarn add -D babel-plugin-transform-es2015-modules-commonjs --dev
affter_success:
  - firebase deploy --token $FIREBASE_TOKEN